version: '3.8'

services:
  api-1:
    build:
      context: ../api-1
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../api-1:/var/www/html
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      DB_NAME: fipe_db
      DB_USER: user
      DB_PASSWORD: password

  api-2:
    build:
      context: ../api-2
      dockerfile: Dockerfile
    volumes:
      - ../api-2:/var/www/html
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      DB_NAME: fipe_db
      DB_USER: user
      DB_PASSWORD: password

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fipe_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

volumes:
  db_data:

